wpa-supplicant: enable WPA open source supplicant build [auto* template update]
Signed-off-by: Inaky Perez-Gonzalez <inaky.perez-gonzalez@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -792,6 +792,9 @@ LIBOBJS
 WPA_SUP_ENABLE_FALSE
 WPA_SUP_ENABLE_TRUE
 WPA_SUP_PREFIX
+LIBEAP0_PREFIX
+LIBEAP0_LIBS
+LIBEAP0_CFLAGS
 VER_INFO_BIN
 WIMAX_DB_BIN
 BINDB_ENABLED_FALSE
@@ -940,7 +943,9 @@ CPPFLAGS
 CPP
 PKG_CONFIG
 LIBWIMAX_CFLAGS
-LIBWIMAX_LIBS'
+LIBWIMAX_LIBS
+LIBEAP0_CFLAGS
+LIBEAP0_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1625,6 +1630,10 @@ Some influential environment variables:
               C compiler flags for LIBWIMAX, overriding pkg-config
   LIBWIMAX_LIBS
               linker flags for LIBWIMAX, overriding pkg-config
+  LIBEAP0_CFLAGS
+              C compiler flags for LIBEAP0, overriding pkg-config
+  LIBEAP0_LIBS
+              linker flags for LIBEAP0, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -4500,13 +4509,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4503: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4512: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4506: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4515: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4509: output\"" >&5)
+  (eval echo "\"\$as_me:4518: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5712,7 +5721,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5715 "configure"' > conftest.$ac_ext
+  echo '#line 5724 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7565,11 +7574,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7568: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7577: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7572: \$? = $ac_status" >&5
+   echo "$as_me:7581: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7904,11 +7913,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7907: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7916: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7911: \$? = $ac_status" >&5
+   echo "$as_me:7920: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8009,11 +8018,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8012: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8021: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8016: \$? = $ac_status" >&5
+   echo "$as_me:8025: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8064,11 +8073,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8067: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8076: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8071: \$? = $ac_status" >&5
+   echo "$as_me:8080: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10867,7 +10876,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10870 "configure"
+#line 10879 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10963,7 +10972,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10966 "configure"
+#line 10975 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11771,11 +11780,20 @@ else
 fi
 
 
-with_sup_wpa=/usr
 
 # Check whether --with-sup-wpa was given.
 if test "${with_sup_wpa+set}" = set; then
   withval=$with_sup_wpa;
+                test -z "$with_sup_wpa" && with_sup_wpa=/usr
+                test x"$with_sup_wpa" = xyes && with_sup_wpa=/usr
+                enable_sup_wpa=yes
+                enable_sup_ds=no
+                export PKG_CONFIG_PATH="$with_sup_wpa:$with_sup_wpa/lib/pkgconfig:$PKG_CONFIG_PATH"
+
+else
+
+                with_sup_wpa=/usr
+
 fi
 
 
@@ -11786,11 +11804,122 @@ $as_echo "supplicant: configured DS binary supplicant" >&6; }
         enable_sup_wpa=no
 else
         enable_sup_wpa=yes
-	{ $as_echo "$as_me:$LINENO: result: supplicant: configured WPA open source supplicant from $with_sup_wpa" >&5
-$as_echo "supplicant: configured WPA open source supplicant from $with_sup_wpa" >&6; }
-        { { $as_echo "$as_me:$LINENO: error: FIXME: not finished, need to detect the supplicant library" >&5
-$as_echo "$as_me: error: FIXME: not finished, need to detect the supplicant library" >&2;}
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for LIBEAP0" >&5
+$as_echo_n "checking for LIBEAP0... " >&6; }
+
+if test -n "$LIBEAP0_CFLAGS"; then
+    pkg_cv_LIBEAP0_CFLAGS="$LIBEAP0_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libeap0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libeap0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBEAP0_CFLAGS=`$PKG_CONFIG --cflags "libeap0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$LIBEAP0_LIBS"; then
+    pkg_cv_LIBEAP0_LIBS="$LIBEAP0_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libeap0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libeap0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBEAP0_LIBS=`$PKG_CONFIG --libs "libeap0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBEAP0_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libeap0" 2>&1`
+        else
+	        LIBEAP0_PKG_ERRORS=`$PKG_CONFIG --print-errors "libeap0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBEAP0_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libeap0) were not met:
+
+$LIBEAP0_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LIBEAP0_CFLAGS
+and LIBEAP0_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libeap0) were not met:
+
+$LIBEAP0_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LIBEAP0_CFLAGS
+and LIBEAP0_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LIBEAP0_CFLAGS
+and LIBEAP0_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LIBEAP0_CFLAGS
+and LIBEAP0_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	LIBEAP0_CFLAGS=$pkg_cv_LIBEAP0_CFLAGS
+	LIBEAP0_LIBS=$pkg_cv_LIBEAP0_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+        libeap0_prefix=`pkg-config libeap0 --variable=prefix`
+        { $as_echo "$as_me:$LINENO: result: Using EAP library from $libeap0_prefix" >&5
+$as_echo "Using EAP library from $libeap0_prefix" >&6; }
+
+
+        LIBEAP0_PREFIX=$libeap0_prefix
+
 fi
 WPA_SUP_PREFIX=$with_sup_wpa
 
